### ISSUE TITLE
Use in shiny package development

### ISSUE THREAD

**Issue by Jeff-Thompson12** [stla/jsTreeR#14]
Can the usage be extended for instances in which a user does not want to attach `{jsTreeR}`? For instance, I do work on developing Shiny applications that are distributed as packages. This results in no formal attaching of `{jsTreeR}` (e.g. `library(jsTreeR)`), but instead will load `{jsTreeR}` functions in the namespace. Since the package is never attached, the JS handlers are never created.

Would you consider switching from `.onAttach()` to `.onLoad()`, or including a helper function (e.g. `use_jsTree()`) that can be called in the server function of a Shiny app?

**Comment by stla** [comment]
Hello,
I'm not a master of `.onAttach` and `.onLoad`. I think I understand the difference (package attached vs package only loaded), but is there a possible inconvenient of using `.onLoad`? I don't think so but I'd like to be sure before switching. I think `.onLoad` is better because that should give the possibility to do `jsTreerR::xxx` without doing `library(jsTreeR)`, right?

**Comment by stla** [comment]
I will probably do the change if you think too there's no possible inconvenient. In the meantime you can use `attachNamespace` in your package.

**Comment by Jeff-Thompson12** [comment]
I am also not a master of these things. My understanding is that `.onAttach` is to be used in interactive user settings like how the `tidyverse` will display messages about which functions has been masked when attaching a package. Running `library(jsTreeR)` will also trigger the load event. I do believe it fits the intended usage here.

**Comment by stla** [comment]
Ok, I do the change. I'll notify you whenever I push.

**Comment by stla** [comment]
Done, you can install the package from the Github repo. I'll send it to CRAN tomorrow or Monday. Cheers.
